name: pytest&flake8

on:
  - push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: make install
      - name: Run linter
        run: make lint
      - name: Run tests
        run: make test
      - name: Run coverage
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: bcd31579e794e37d2c6ff23f7af343dd8132ce1afd6a919bdd04d4baf6e70f5a
        with:
          coverageCommand: poetry run coverage report